config/routes.rb
Rails.application.routes.draw do
  resources :songs
  get 'scan' => 'uploads#new'
  post 'scan' => 'uploads#create'

end

app/models/song.rb
class Song < ActiveRecord::Base
	validates :title, presence: true
	validates :artist, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = Song.all
  end

  def show

  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to songs_path
    else
      render action: 'new'
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update
      redirect_to songs_path
    else
      render action: 'edit'
    end
  end

  def destroy

  end

  private

    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:title, :artist, :album, :year, :track, :genre)
    end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
	require 'taglib'

	def new
	end

	def create

		params[:uploads].each do |uploaded_io| 
			File.open(Rails.root.join('public', 'songs_temp', uploaded_io.original_filename),
				'wb') do |file|
				file.write(uploaded_io.read)
			end

			file_path = "public/songs_temp/#{uploaded_io.original_filename}"
			TagLib::FileRef.open(file_path) do |fileref|
				unless fileref.null?
					tag = fileref.tag
					# properties = fileref.audio_properties
					@song = Song.new(title: tag.title, artist: tag.artist, album: tag.album,
						year: tag.year, track: tag.track, genre: tag.genre)
					File.delete(file_path)
					if @song.save
						
					else
						render 'new'
					end
				else
					flash.now[:error] = "File could not be read"
					render 'new'
				end
			end
		end
		redirect_to songs_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
	<p><%=msg%></p>
<%end%>

app/views/layouts/_footer.html.erb
<footer class='the_footer'>
  <p><font color='#A9BCF5'>Copyright</font> <em>Jose Tello / Derek Maffett 2014</em></p>
</footer>

app/views/layouts/_header.html.erb
<header class='main_header'>
  <nav class='navbar'>
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </nav>
</header>

app/views/layouts/_navigation_links.html.erb
<%= link_to "Home", '#' %>
<%= link_to "Music", '#' %>
<%= link_to "Resources", '#' %>
<%= link_to "About", '#' %>
<%= link_to "Contact", '#' %>

app/views/layouts/_sidebar.html.erb
<aside class='sidebar'>
  <div class='top_sidebar'>
    <header>
      <h2>Login</h2>
      <p><em>Not registered? Sign up only takes a moment!</em></p>
    </header>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head class='the_header'>
  <%= image_tag "Setlist_Header_01.png", class: "banner" %>
  <title>Setlist</title>
  
  <meta charset='utf-8'/>
  <meta name='viewport' content='width=device-width, initial-scale-1.0'>  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body class='body'>
<%= render 'layouts/flash' %>
<%= render 'layouts/header' %>
<%# render 'layouts/sidebar' %>

<%= yield %>



<%= render 'layouts/footer' %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%# too many breaks, revise with css %>
    <%= f.label :title %> <br />
    <%= f.text_field :title %> <br />

    <%= f.label :artist %> <br />
    <%= f.text_field :artist %> <br />

    <%= f.label :album %> <br />
    <%= f.text_field :album %> <br />

    <%= f.label :year %> <br />
    <%= f.text_field :year %> <br />

    <%= f.label :track %> <br />
    <%= f.text_field :track %> <br />

    <%= f.label :genre %> <br />
    <%= f.text_field :genre %> <br />

    <br />
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<tr>
	<td colspan="1"><%= song.title %> </td>
	<td colspan="1"><%= song.artist %> </td>
	<td colspan="1"><%= song.album %> </td>
	<td colspan="1"><%= song.year %> </td>
	<td colspan="1"><%= song.track %> </td>
	<td colspan="1"><%= song.genre %> </td>
</tr>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <thead>
    <tr>
      <th colspan="1">Title</th>
      <th colspan="1">Artist</th>
      <th colspan="1">Album</th>
      <th colspan="1">Year</th>
      <th colspan="1">Track</th>
      <th colspan="1">Genre</th>
    </tr>
  </thead>

  <tbody>
    <%= render @songs %>
  </tbody>
</table>

<br>

<%# link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

app/views/uploads/new.html.erb
<h1> Mass Upload </h1>

<%= form_tag({ action: :create }, { multipart: true }) do %>
	
	<%= label_tag :uploads, "Scan your song:" %>
	<%= file_field_tag :uploads, name: 'uploads[]', multiple: true %>

	<br />
	<%= submit_tag "Submit" %>

<% end %>